using System.Text;
using SkiaSharp;

namespace BkyhBot.BotConnect
{
	public static class ImageMaker
	{
		// 定义一些常量：字体大小、边距、颜色
		private const int Width = 600; // 图片固定宽度
		private const int Padding = 40; // 内边距
		private const int HeaderHeight = 80; // 头部高度(显示昵称)
		private const float FontSizeName = 32; // 昵称字号
		private const float FontSizeText = 28; // 正文字号
		private const float LineHeight = 40; // 正文行高

		/// <summary>
		/// 绘制文字卡片并返回 CQ 码
		/// </summary>
		/// <param name="name">发送者昵称</param>
		/// <param name="text">消息内容</param>
		/// <returns>[CQ:image,file=base64://...]</returns>
		public static string MakeTextCard(string name, string text)
		{
			// 1. 准备画笔
			using var paintName = new SKPaint
			{
				Color = SKColors.Black,
				TextSize = FontSizeName,
				IsAntialias = true,
				Typeface = SKTypeface.FromFamilyName("Microsoft YaHei", SKFontStyle.Bold) // 尝试使用微软雅黑粗体
			};

			using var paintText = new SKPaint
			{
				Color = SKColors.DarkGray,
				TextSize = FontSizeText,
				IsAntialias = true,
				Typeface = SKTypeface.FromFamilyName("Microsoft YaHei")
			};

			using var paintBg = new SKPaint { Color = SKColors.White };

			// 2. 计算文字换行 (SkiaSharp 不会自动换行，需要手动算)
			var lines = WrapText(text, paintText, Width - Padding * 2);

			// 3. 计算图片总高度
			int contentHeight = (int)(lines.Count * LineHeight);
			int totalHeight = HeaderHeight + contentHeight + Padding * 2;

			// 4. 创建画布
			using var surface = SKSurface.Create(new SKImageInfo(Width, totalHeight));
			var canvas = surface.Canvas;

			// 5. 开始绘制
			// --- 背景 ---
			canvas.Clear(SKColors.WhiteSmoke); // 浅灰色底

			// 画一个圆角矩形做卡片主体
			using var cardPaint = new SKPaint { Color = SKColors.White, IsAntialias = true };
			cardPaint.Shader = SKShader.CreateLinearGradient(
				new SKPoint(0, 0), new SKPoint(0, totalHeight),
				new SKColor[] { SKColors.White, SKColors.FloralWhite },
				null, SKShaderTileMode.Clamp);

			canvas.DrawRoundRect(new SKRect(20, 20, Width - 20, totalHeight - 20), 30, 30, cardPaint);

			// --- 头部 (昵称) ---
			// 画一条装饰线
			using var linePaint = new SKPaint { Color = SKColors.LightBlue, StrokeWidth = 5 };
			canvas.DrawLine(Padding, HeaderHeight, Width - Padding, HeaderHeight, linePaint);

			// 写昵称
			canvas.DrawText($"{name}", Padding, Padding + FontSizeName, paintName);

			// --- 正文 ---
			float y = HeaderHeight + Padding + FontSizeText;
			foreach (var line in lines)
			{
				canvas.DrawText(line, Padding, y, paintText);
				y += LineHeight;
			}

			// --- 水印 (可选) ---
			/*
			using var watermarkPaint = new SKPaint
			{
				Color = new SKColor(200, 200, 200, 100),
				TextSize = 20
			};
			canvas.DrawText($"Generated by BkyhBot @ {DateTime.Now:HH:mm}", Width - 280, totalHeight - 30, watermarkPaint);

			*/
			// 6. 导出为 Base64
			using var image = surface.Snapshot();
			using var data = image.Encode(SKEncodedImageFormat.Png, 100);
			string base64 = Convert.ToBase64String(data.ToArray());

			// 返回 OneBot 格式的 Base64 图片代码
			return $"[CQ:image,file=base64://{base64}]";
		}

		/// <summary>
		/// 辅助方法：文本自动换行算法
		/// </summary>
		private static List<string> WrapText(string text, SKPaint paint, float maxWidth)
		{
			var lines = new List<string>();
			var sb = new StringBuilder();

			foreach (var word in text) // 这是一个简单的按字符拆分，你可以优化为按词拆分
			{
				// 试探性加入一个字符
				string testLine = sb.ToString() + word;
				// 测量宽度
				float width = paint.MeasureText(testLine);

				if (width > maxWidth)
				{
					// 如果超宽了，就把之前的存为一行，重新开始
					lines.Add(sb.ToString());
					sb.Clear();
					sb.Append(word);
				}
				else
				{
					sb.Append(word);
				}
			}

			// 把最后剩下的也加进去
			if (sb.Length > 0) lines.Add(sb.ToString());

			return lines;
		}
	}
}